// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScreens() {
  return window['go']['main']['App']['GetScreens']();
}

export function MinimiseAppScreen() {
  return window['go']['main']['App']['MinimiseAppScreen']();
}
